site_name: Kitchen cookbook for the home
repo_url: https://gitlab.openstorage.io/apinter/cookbok
edit_uri: ""

plugins:
    - search
    - git-revision-date
      #- mkdocs-versioning:
      #  version: 0.0.1
    - pdf-export:
        verbose: true
        media_type: print
        #enable PDF printing by running "export ENABLE_PDF_EXPORT=1"
        enabled_if_env: ENABLE_PDF_EXPORT
        #comment out the next two options to make every page have its own PDF
        combined: true
        combined_output_path: docs.pdf
        
theme:
    name: material
    font: true
    custom_dir: overrides
    palette:
        scheme: preference
        primary: purple
        accent: black 
    logo: image/hat.svg
    favicon: image/hat_fav.png
    features:
        - navigation.instant
        - navigation.instant
        - navigation.tracking
        # - navigation.expand

    icon:
        repo: fontawesome/brands/gitlab

extra:
    logo: image/geeko-color.png
    social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.openstorage.io/apinter/cookbok
      name: Cookbook on Gitlab

extra_css: 
    - styles.css
      
markdown_extensions:
    - admonition
    - def_list
    - pymdownx.details
    - pymdownx.superfences
    - toc:
        permalink: ⚓︎
        toc_depth: 5

nav:
    - Home: index.md
      #- Version Selector: "../"
    - Favorites: ""
    - Desserts: 
        - Crepes: "crepes.md"
        - American Pancakes: ""
        - Apple pie: ""
    - Mains: 
        - Vegan: ""
        - Asian:
            - Gorengan (tempe): ""
            - Gorengan (bakwan jagung): ""
            - Bakso: ""
            - Shanghai style eggplants: ""
            - Broccoli stir fries: ""
        - Pasta:
            - Spaghetti:  ""
            - Black pepper fetuccini: ""
            - Alfredo: ""
        - Beef:
            - Burger: ""
            - Steak: ""
            - Gulyas soup: ""
        - Chicken: 
            - Chicken fingers sandwich: ""
            - Chicken paprikas: ""
        - Fish:
            - Tuna melt sandwich: ""
            - Tuna fish cakes: ""